version: 2
updates:
  - package-ecosystem: "bundler"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"

    # Group packages into shared PR
    groups:
      rubocop:
        patterns:
          - 'rubocop'
          - 'rubocop-*'

      axe:
        patterns:
          - 'axe*'

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"
