---
plugins:
    - rubocop-rspec

require:
    - rubocop-capybara

AllCops:
    NewCops: enable
    TargetRubyVersion: 3.4

# Capyabara rubocop config
Capybara:
    Enabled: true

Capybara/ClickLinkOrButtonStyle:
    Enabled: false

# RSpec rubocop config
RSpec:
    Enabled: true

RSpec/MultipleExpectations:
    Max: 3
    Exclude:
        - "spec/features/**/*"

RSpec/ExampleLength:
    Max: 10
    Exclude:
        - "spec/features/**/*"

RSpec/MultipleMemoizedHelpers:
    Enabled: false

RSpec/VariableName:
    Enabled: false

# Standard rubocop config
Style/Alias:
    Enabled: false

Style/FrozenStringLiteralComment:
    Enabled: false

Style/NumericLiterals:
    Enabled: false

Style/TrailingCommaInArrayLiteral:
    Enabled: false

Style/TrailingCommaInHashLiteral:
    Enabled: false

Style/TrailingCommaInArguments:
    Enabled: false

Style/Documentation:
    Enabled: false

Style/DoubleNegation:
    Enabled: false

Style/WordArray:
    Enabled: false

Style/ClassAndModuleChildren:
    Enabled: false

Layout/EndOfLine:
    EnforcedStyle: lf

Layout/TrailingEmptyLines:
    Enabled: true

Layout/LineLength:
    Max: 120
    Enabled: false

Metrics/ClassLength:
    Enabled: false

Metrics/MethodLength:
    Max: 50
    Exclude:

Metrics/AbcSize:
    Max: 25 # TODO: Restore to '20'

Metrics/BlockLength:
    Max: 40

Naming/VariableNumber:
    Enabled: false

Lint/MissingSuper:
    Enabled: false

Style/OptionalBooleanParameter:
    Enabled: false
