---
users:
  admin:
    facilities_management:
      email:
      password:
    management_consultancy:
      email:
      password:
    legal_services:
      email:
      password:
    supply_teachers:
      email:
      password:
  buyer:
    facilities_management:
      email:
      password:
    management_consultancy:
      email:
      password:
    legal_services:
      email:
      password:
    supply_teachers:
      email:
      password:
    no_details:
      email:
      password: