---
local:
  host: http://localhost
  live_services:
    - service: facilities_management
      frameworks: 
        - RM6232
        - RM6378
    - service: legal_panel_for_government
      frameworks: 
        - RM6360
    - service: legal_services
      frameworks: 
        - RM6240
    - service: management_consultancy
      frameworks: 
        - RM6187
        - RM6309
    - service: supply_teachers
      frameworks: 
        - RM6238
        - RM6376
sandbox:
  host: https://cmp.cmp-sandbox.gca.gov.uk
  live_services:
    - service: facilities_management
      frameworks: 
        - RM6232
        - RM6378
    - service: legal_panel_for_government
      frameworks: 
        - RM6360
    - service: legal_services
      frameworks: 
        - RM6240
    - service: management_consultancy
      frameworks: 
        - RM6187
        - RM6309
    - service: supply_teachers
      frameworks: 
        - RM6238
        - RM6376
cmpdev:
  host: https://cmp.cmpdev.gca.gov.uk
  live_services:
    - service: facilities_management
      frameworks: 
        - RM6232
        - RM6378
    - service: legal_panel_for_government
      frameworks: 
        - RM6360
    - service: legal_services
      frameworks: 
        - RM6240
    - service: management_consultancy
      frameworks: 
        - RM6187
        - RM6309
    - service: supply_teachers
      frameworks: 
        - RM6238
        - RM6376
preview:
  host: https://marketplace.preview.gca.gov.uk
  live_services:
    - service: facilities_management
      frameworks: 
        - RM6232
        - RM6378
    - service: legal_panel_for_government
      frameworks: 
        - RM6360
    - service: legal_services
      frameworks: 
        - RM6240
    - service: management_consultancy
      frameworks:
        - RM6309
    - service: supply_teachers
      frameworks: 
        - RM6238
        - RM6376
production:
  host: https://marketplace.service.gca.gov.uk
  live_services:
    - service: facilities_management
      frameworks: 
        - RM6232
    - service: legal_services
      frameworks: 
        - RM6240
    - service: legal_panel_for_government
      frameworks: 
        - RM6360
    - service: management_consultancy
      frameworks: 
        - RM6309
    - service: supply_teachers
      frameworks: 
        - RM6238
        - RM6376
